### ISSUE TITLE
General Code Refactor

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#121]
The code of the CLI can go through these improve list to be easier to maintain and add more things in the future.
[This design lists the changes planned to be done](https://github.com/cyberark/conjur-api-python3/blob/master/design/general_refactorings.md) 

DOD:
- [x] Organize directory structure [Top Priority!]
- [ ] Improve Error Handling - [Opened Issue](https://github.com/cyberark/conjur-api-python3/issues/194)
- [ ] Strong-type function parameters and return types - [Opened Issue](https://github.com/cyberark/conjur-api-python3/issues/193)
- [x] Explicit Import Statements

**Comment by tzheleznyak** [comment]
- [ ] Reorder Conjur Directory to have directories as class type : data_objects, controllers, logics, wrappers, consts, exceptions -  1 Day
- [ ] <Mentioned Above> Improve error handling. Investigate placing our errors in their own error.py file. See here for example -  1 Day
- [ ] Return Types To Functions - 1 Day
- [ ] Type Of Parameters In All Functions - 1 Day
- [ ] Add urlparse in ConjurrcData instead of appliance_url being a string because we have urlparse in multiple places. Also, extract url validations from init_controller - 1 Day
- [ ] Handle When conjurrc field don't exist - 1 Day
- [ ] <Mentioned Above> Refactor cli.py because it currently has multiple responsibility which breaks SOLID and make that class a factory method This issue lists all suggestions made that were unable to be addressed during the time allotted to finishing the init command - 3 Day
- [ ] <Mentioned Above> Evaluate moving to click instead of argparse. If work it, make the change - 3 Day
- [ ] <Mentioned Above> Add better error handling when user writes http instead of https because this is something we don't officially support - 1 Day
- [ ] Naming Refactoring - 1 Day
- [ ] Do Renamings In the code where needed - 1 Day
- [ ] Add father classes to collections, logics, data_objects. to be OOP - 1 Day
- [ ] Base Function to classes that inherit from same class? - 2 Days

**Comment by abrahamko** [comment]
This list is too vague.
What does `Genegal code refactor` includes?
Please list exactly what you plan to do, so you could know when you're finished.
Even if the list is huge, full of little tasks, you could finish it small parts at a time.
At least you will know for sure when a task is done.

**Comment by Tovli** [comment]
I agree with @abrahamko - it is not clear what are you trying to achieve here

**Comment by izgeri** [comment]
is this more `kind/developer-experience` than `kind/enhancement`? Enhancements are usually new features or functionality that we're deliver to end-users.
