### ISSUE TITLE
CLI - Differences between Windows Server and Windows 10

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#241]
We need to support the CLI running on Windows 10. To say we officially support that the CLI runs on Windows 10 we need to test on a Windows machine. Up until now the CLI integration tests have been running on an AMI whose base is 'Windows Server 2016 Base 10' with a Windows 10 GUI. Therefore we need to research what the differences are between the base image used to run our tests currently and a regular Windows 10 machine.

** This is a task because AWS might not offer pure Windows 10 machines and we will need to decide what to do

DOD
- [x] Research the differences between Windows Server 2016/9 Base 10 and a regular Windows 10 machine and decide if the differences between them are minute enough to not have to run our test infra on a regular Windows 10 machine. Important areas of comparison include: credential store!
- [x] If not minor, figure out how to spin up a Windows 10 machine that won't be hard to replicate. Brownie points if we can find a way to spin one up in AWS so all our tests can be run in a single platform!

**Comment by abrahamko** [comment]
### Concerns
Win 10 credentials store behaves differently from Windows Server 2016, and might hide an unknown bug.

### Actions taken
#### 1. Test CLI in Windows 10
Result: CLI works properly, and credentials are successfully stored and retrieved from internal credentials store.
The following python code snippet was used to verify it:
```
python -c "import keyring; print(keyring.get_keyring()); print(keyring.get_password(\"https://sigallb.aim-dev.conjur.net\", \"login\")); print(keyring.get_password(\"https://sigallb.aim-dev.conjur.net\", \"password\"))"
```

#### 2. Investigate Win 10 deployment in AWS
Investigation in the direction of running a proper VM of Win 10 in AWS concluded that it is possible, but we need to supply its VM for deployment.

 * This can be done using a VM snapshot file of clean Win 10 such as VHDX.
   (See [this Stack Overflow answer](https://stackoverflow.com/a/47107748/3997365) for more info)
* Clean Win 10 VHDX can be officially downloaded freely from Microsoft site here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
   NOTE: Once machine is started it will expire in 90 days. (See for more info: https://www.scivision.dev/free-windows-virtual-machine-images/)
* Then this file can be used to create AMI, for example by following this guide: https://jamalahmed.wordpress.com/2016/12/29/convert-vmdk-to-aws-ami/

#### 3. Investigate the differences between Win 10 and Windows Server 2016 around credentials store
Investigating the differences between Win 10 and Win Server 2016 around credentials store led me to this Microsoft doc: https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/credentials-processes-in-windows-authentication
I couldn't conclude any difference between those OS flavors around credentials store.

### Conclusions
1. CLI works as expected in Windows 10, also for storing its credentials in internal credentials store.
2. No apparent reason was found to raise a need to test explicitly on Win 10 instead of Windows Server 2016.
3. Keep testing on Windows Server 2016 AMI in AWS.
4. In case the need to test regularly on Win 10, it can be done by following the guidelines mentioned above.
